version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ../pgdata:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1999
      - POSTGRES_DB=animalservice

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    restart: always
    ports:
      - "8000:8080"

  animalservice:
    build:
      context: .
    container_name: service
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - spring.config.location=classpath:/application.properties
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/animalservice
